stackclient2: stackclient2.o stackADT2.o
	gcc -o build/stackclient2 build/stackclient2.o build/stackADT2.o

stackclient2.o: stackclient2.c stackADT2.h
	gcc -c stackclient2.c -o build/stackclient2.o

stackADT2.o: stackADT2.c stackADT2.h
	gcc -c stackADT2.c -o build/stackADT2.o
