parantheses: parantheses.o stackADT3.o
	gcc -o build/parantheses build/parantheses.o build/stackADT3.o

parantheses.o: parantheses.c stackADT.h
	gcc -c parantheses.c -o ./build/parantheses.o	

stackADT3.o: stackADT3.c stackADT.h
	gcc -c stackADT3.c -o ./build/stackADT3.o 
